### ISSUE TITLE
Please update the metadata in theme.toml

### ISSUE THREAD

**Issue by digitalcraftsman** [nsomar/github-project-landing-page#7]
Hello @nsomar 

in https://github.com/gohugoio/hugoThemes/issues/269 a user reported that some broke on the hugo theme site because the theme.toml refers to swiftline as the repository owner.

Would you mind to update the metadata in the theme.toml?

Regards,
Digitalcraftsman

**Comment by nsomar** [comment]
Hello @digitalcraftsman sorry for being so late. This has been fixed now
